# Generated by Django 6.0.7 on 2026-07-10 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('usuario_bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_bloqueador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('ocultar_ubicacion', models.BooleanField(default=False)),
                ('preferencia_interfaz', models.CharField(default='claro', max_length=50)),
                ('reputacion', models.FloatField(default=5.0)),
                ('estado_cuenta', models.CharField(default='ACTIVA', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
