# Generated by Django 6.0.7 on 2026-07-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_match', models.DateTimeField(auto_now_add=True)),
                ('gato_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_enviados', to='cats.cat')),
                ('gato_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_recibidos', to='cats.cat')),
            ],
        ),
    ]
