# Generated by Django 6.0.7 on 2026-07-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ADOPTADO', 'Adoptado')], default='DISPONIBLE', max_length=20)),
                ('publicado_en', models.DateTimeField(auto_now_add=True)),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
            ],
        ),
    ]
