# Generated by Django 6.0.7 on 2026-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionpost',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADA', 'Reservada'), ('ADOPTADA', 'Adoptada')], default='DISPONIBLE', max_length=20),
        ),
    ]
