# Generated by Django 6.0.7 on 2026-07-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='soporte',
            field=models.FileField(blank=True, null=True, upload_to='vaccines/'),
        ),
    ]
