# Generated by Django 6.0.7 on 2026-07-28 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_medicalrecord_documento_vaccine_soporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cats/gallery/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cats.cat')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
